server_url: http://headscale:8080
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 127.0.0.1:9090
grpc_listen_addr: 127.0.0.1:50443
grpc_allow_insecure: true

noise:
  private_key_path: /var/lib/headscale/noise_private.key
ip_prefixes:
  - fd7a:115c:a1e0::/48
  - 100.64.0.0/10

derp:
  server:
    enabled: true
    region_id: 999
    region_code: "headscale"
    region_name: "Headscale Embedded DERP"
    stun_listen_addr: "0.0.0.0:3478"
    private_key_path: /var/lib/headscale/derp_server_private.key
  paths: []
  auto_update_enabled: true
  update_frequency: 24h

disable_check_updates: true
ephemeral_node_inactivity_timeout: 120s
node_update_check_interval: 10s

db_type: postgres
db_host: postgres
db_port: 5432
db_name: postgres
db_user: postgres
db_pass: postgres
db_ssl: false

log:
  format: json
  level: info

acl_policy_path: "/etc/headscale/acl.json"

dns_config:
  override_local_dns: false
  nameservers:
    - 1.1.1.1

  domains: []
  magic_dns: false
  base_domain: host.local

unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"
logtail:
  enabled: false

randomize_client_port: false

